name: fhir
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
version: 0.11.5-dev3
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  uuid: ^4.3.1
  xml2json: ^6.2.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  test: ^1.25.0
